Edari/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('shop.urls')),
    path('', include('organization.urls')),
]

organization/urls.py
from django.urls import path
from . import views


app_name = 'organization'

urlpatterns = [
    path('vacation-request', views.vacation_request, name='vacation_request'),
    path('vacation-requests', views.vacation_requests, name='vacation_requests'),
    path('alternative-requests', views.alternative_request_logs, name='alternative_requests'),
    path('vacation-requests/<int:pk>', views.vacation_request_review, name='vacation_request_review'),
    path('alternative-requests/<int:pk>', views.alter_request_review, name='alternative_request_review'),
    path('vacation-request-logs', views.vacation_request_logs, name='vacation_request_logs'),
    path('problem-report', views.problem_report, name='problem_report'),
    path('problem-reports', views.problem_reports, name='problem_reports'),
    path('problem-report-logs', views.problem_report_logs, name='problem_report_logs'),
    path('export-pdf/<str:content>', views.export_to_pdf, name='export_pdf')
]

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    path('product-buy-order', views.buy_order, name='buy_order'),
    path('product-buy-orders', views.buy_orders, name='buy_orders'),
    path('product-buy-orders/<int:pk>', views.buy_order_review, name='buy_order_review'),
    path('product-buy-orders-logs', views.buy_order_logs, name='buy_order_logs'),
    path('product-from-stockroom', views.stockroom_order, name='stockroom_order'),
    path('product-requests-stockroom', views.stockroom_orders, name='stockroom_orders'),
    path('product-requests-stockroom/<int:pk>', views.stockroom_order_review, name='stockroom_order_review'),
    path('product-from-stockroom-logs', views.stockroom_order_logs, name='stockroom_order_logs'),
]

organization/models.py
from django.conf import settings
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone


VACATION_TYPE = [
    ("ساعتی", "ساعتی"),
    ("روزانه", "روزانه")
]


VACATION_STATUS = [
    ("بررسی نشده", "بررسی نشده"),
    ("تایید جانشین", "تایید جانشین"),
    ("رد جانشین", "رد جانشین"),
    ("موافقت شده", "موافقت شده"),
    ("رد شده", "رد شده")
]


class Log(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             related_name="user_actions",
                             verbose_name="کاربر")
    action = models.TextField(max_length=250,
                            blank=True,
                            verbose_name="عمل انجام شده")
    created = models.DateTimeField(auto_now_add=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    def __str__(self):
        return str(f"لاگ شماره: {self.pk}")

    class Meta:
        verbose_name = 'لاگ'
        verbose_name_plural = 'لاگ ها'
        indexes = [
            models.Index(fields=["content_type", "object_id"]),
        ]


class VacationRequest(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             related_name="user_vacation_req",
                             verbose_name="نام متقاضی")
    alternative = models.ForeignKey(settings.AUTH_USER_MODEL,
                                    on_delete=models.CASCADE,
                                    related_name="alter_vacation_req",
                                    verbose_name="جایگزین")
    start_date = models.DateTimeField(blank=False,
                                      verbose_name="تاریخ شروع")
    end_date = models.DateTimeField(blank=False,
                                    verbose_name="تاریخ پایان")
    duration = models.PositiveIntegerField(verbose_name="مدت")
    type = models.CharField(max_length=20,
                            choices=VACATION_TYPE,
                            verbose_name="نوع مرخصی")
    description = models.TextField(max_length=250,
                                   blank=True,
                                   verbose_name="توضیحات")
    status = models.CharField(max_length=20,
                              choices=VACATION_STATUS,
                              default="بررسی نشده",
                              verbose_name="وضعیت مرخصی")
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'درخواست مرخصی'
        verbose_name_plural = 'درخواست های مرخصی'

    def __str__(self):
        return str(f'مرخصی {self.type} برای {self.user}')


class ProblemReport(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             related_name="user_problem_reports",
                             verbose_name="اعلام کننده")
    type = models.CharField(max_length=50,
                            blank=False,
                            verbose_name="نوع خطا")
    description = models.TextField(max_length=250,
                                   blank=True,
                                   verbose_name="توضیحات")
    corrective_actions = models.TextField(max_length=250,
                                          blank=True,
                                          verbose_name="اقدامات اصلاحی")
    prevention_actions = models.TextField(max_length=250,
                                          blank=True,
                                          verbose_name="اقدامات پیشگیری")
    effective = models.BooleanField(default=True,
                                    verbose_name="مؤثر بوده/نبوده")
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'ثبت خطا'
        verbose_name_plural = 'خطاهای ثبت شده'

    def __str__(self):
        return str(self.type)

organization/views.py
import datetime
from re import search
from jalali_date_new.utils import to_georgian
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from .forms import VacationRequestForm, ProblemReportForm,\
    VacationRequestBossReviewForm, VacationRequestAlterReviewForm, SearchForm, ProblemSearchForm
from .models import VacationRequest, ProblemReport, Log
from shop.models import ProductBuyOrder, ProductStockroomOrder
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, FileResponse
from django.core.exceptions import PermissionDenied
from common import export


"""
Views for handling vacation requests written below:
Add, View, Update operations

Requires being signed in with @login_required() decorator

Accessibility and permission allowing included for each one by @permission_required() decorator:
add permission -> add_vacationrequest
view and update permission -> view_vacationrequest
"""

# new vacation request
@login_required
@permission_required("organization.add_vacationrequest", raise_exception=True)
def vacation_request(request):
    if request.method == 'POST':
        form = VacationRequestForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new = form.save(commit=False)
            new.user = request.user
            new.save()

            return redirect('organization:vacation_requests')
    else:
        form = VacationRequestForm(data=request.GET)

        return render(request, "VacationRequest.html",
                      {"title": "درخواست مرخصی",
                       "user": request.user,
                       "form": form
                       })


# admin vacation request review and update
@login_required
@permission_required("organization.view_vacationrequest", raise_exception=True)
def vacation_request_review(request, pk):
    instance = VacationRequest.objects.get(id=pk)
    if request.method == 'POST':
        if request.user.has_perm('organization.change_vacationrequest'):
            form = VacationRequestBossReviewForm(data=request.POST, instance=instance)
            if form.has_changed():
                message = f'وضعیت درخواست را از "{instance.status}" به "{form.data['status']}" تغییر داد.'
                Log.objects.create(user=request.user,
                                   action=message,
                                   content_object=instance)
            if form.is_valid():
                form.save()

                return redirect('organization:vacation_request_logs')
        else:
            return PermissionDenied
    else:
        form = VacationRequestBossReviewForm(instance=instance)

        return render(request, "VacationDetail.html",
                      {"title": "جزئیات درخواست مرخصی",
                       "user": request.user,
                       "form": form,
                       "instance": instance
                       })


# alter vacation request review and update
@login_required
@permission_required("organization.add_vacationrequest", raise_exception=True)
def alter_request_review(request, pk):
    instance = VacationRequest.objects.get(id=pk)
    if instance.alternative == request.user:
        if request.method == 'POST':
            form = VacationRequestAlterReviewForm(data=request.POST, instance=instance)
            if form.has_changed():
                message = f'وضعیت درخواست را از "{instance.status}" به "{form.data['status']}" تغییر داد.'
                Log.objects.create(user=request.user,
                                   action=message,
                                   content_object=instance)
            if form.is_valid():
                form.save()

                return redirect('organization:alternative_requests')
        else:
            form = VacationRequestAlterReviewForm(instance=instance)

            return render(request, "VacationDetail.html",
                          {"title": "جزئیات درخواست مرخصی",
                           "user": request.user,
                           "form": form,
                           "instance": instance
                           })
    else:
        return PermissionDenied


# all users vacation request logs for admin
@login_required
@permission_required("organization.view_vacationrequest", raise_exception=True)
def vacation_request_logs(request):
    if request.user.has_perm('organization.change_vacationrequest'):
        logs = VacationRequest.objects.filter(status__in=["تایید جانشین", "موافقت شده", "رد شده"]).order_by("-created")
    else:
        logs = VacationRequest.objects.filter(status="موافقت شده").order_by("-created")

    paginator = Paginator(logs, 15)
    page = request.GET.get("page")
    try:
        logs = paginator.page(page)
    except PageNotAnInteger:
        logs = paginator.page(1)
    except EmptyPage:
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return HttpResponse('')
        logs = paginator.page(paginator.num_pages)

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return render(request, 'VacationLogsActionsAJAX.html',
                      {'logs': logs})

    search_form = SearchForm(data=request.GET)
    return render(request, "VacationLogsActions.html",
                  {"title": "سوابق درخواست مرخصی",
                   "user": request.user,
                   "logs": logs,
                   "action_mode": "boss",
                   "search_form": search_form
                   })


# export request logs to pdf
@login_required
def export_to_pdf(request, content):
    start_date = to_georgian(request.GET.get("start_date"))
    end_date = to_georgian(request.GET.get("end_date")) + datetime.timedelta(days=1)
    all_status = ["بررسی نشده", "بررسی بیشتر", "تایید جانشین", "رد جانشین", "موافقت شده", "رد شده", True, False]
    status = all_status if request.GET.get("status") == 'تمام موارد' else [request.GET.get("status")]
    bool_status = [True, False] if request.GET.get("status") == 'تمام موارد' else [request.GET.get("status")]

    match content:
        case('buy_orders'):
            if request.user.has_perm('shop.view_productbuyorder'):
                logs = ProductBuyOrder.objects.filter(created__range=(start_date, end_date), status__in=status).order_by("-created")
                pdf = export.generate_buy_order_pdf(logs)
                f_name = f'buy-orders.pdf'
                return FileResponse(pdf, as_attachment=True, filename=f_name)
            else:
                raise PermissionDenied

        case('stock_orders'):
            if request.user.has_perm('shop.view_productstockroomorder'):
                logs = ProductStockroomOrder.objects.filter(created__range=(start_date, end_date), status__in=status).order_by("-created")
                pdf = export.generate_stock_order_pdf(logs)
                f_name = f'stock-orders.pdf'
                return FileResponse(pdf, as_attachment=True, filename=f_name)
            else:
                raise PermissionDenied

        case('vacation_reqs'):
            if request.user.has_perm('organization.view_vacationrequest'):
                logs = VacationRequest.objects.filter(created__range=(start_date, end_date), status__in=status).order_by("-created")
                pdf = export.generate_vacation_req_pdf(logs)
                f_name = f'vacation-requests.pdf'
                return FileResponse(pdf, as_attachment=True, filename=f_name)
            else:
                raise PermissionDenied

        case ('problem_reps'):
            if request.user.has_perm('organization.view_problemreport'):
                logs = ProblemReport.objects.filter(created__range=(start_date, end_date),
                                                    effective__in=bool_status).order_by("-created")
                pdf = export.generate_problem_reps_pdf(logs)
                f_name = f'problem-reports.pdf'
                return FileResponse(pdf, as_attachment=True, filename=f_name)
            else:
                raise PermissionDenied


# user vacation request logs
@login_required
@permission_required("organization.add_vacationrequest", raise_exception=True)
def vacation_requests(request):
    logs = VacationRequest.objects.filter(user=request.user).order_by("-created")

    paginator = Paginator(logs, 15)
    page = request.GET.get("page")
    try:
        logs = paginator.page(page)
    except PageNotAnInteger:
        logs = paginator.page(1)
    except EmptyPage:
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return HttpResponse('')
        logs = paginator.page(paginator.num_pages)

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return render(request, 'VacationLogsAJAX.html',
                      {'logs': logs})

    return render(request, "VacationLogs.html",
                  {"title": "وضعیت درخواست مرخصی",
                   "user": request.user,
                   "logs": logs
                   })


# user being alternative requests logs
@login_required
@permission_required("organization.add_vacationrequest", raise_exception=True)
def alternative_request_logs(request):
    logs = request.user.alter_vacation_req.filter(status__in=["تایید جانشین", "رد جانشین", "بررسی نشده"]).order_by("-created")

    paginator = Paginator(logs, 15)
    page = request.GET.get("page")
    try:
        logs = paginator.page(page)
    except PageNotAnInteger:
        logs = paginator.page(1)
    except EmptyPage:
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return HttpResponse('')
        logs = paginator.page(paginator.num_pages)

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return render(request, 'VacationLogsActionsAJAX.html',
                      {'logs': logs})

    return render(request, "VacationLogsActions.html",

organization/templates/ProblemLogs.html
{% extends "base.html" %}
{% load static %}
{% block include %}
<link href="{% static "css/logs.css" %}" rel="stylesheet">
{% endblock %}
{% block content %}
<div id="mainContent">
    <table>
        <tr>
            <th>نوع خطا</th>
            <th>اقدامات اصلاحی</th>
            <th>اقدامات پیشگیری</th>
            <th>توضیحات</th>
            <th>تاریخ</th>
            <th>موثر بوده/نبوده</th>
        </tr>
        {% include "ProblemLogsAJAX.html" %}
    </table>
</div>
<span id="loading" class="custom-loader"></span>
{% endblock %}

{% block domready %}
<script>
    let page = 1;
    let empty_page = false;
    let block_request = false;

    $(window).scroll(function() {
        var margin = $(document).height() - $(window).height() - 50;
        if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
            block_request = true;
            page += 1;
            $.get('?page=' + page, function(data) {
                if(data == '') {
                    empty_page = true;
                }
                else {
                    block_request = false;
                    $(" table ").append(data);
                }
            });
        }
    });
</script>
{% endblock %}

organization/templates/ProblemLogsAJAX.html
{% load to_jalali_datetime %}
{% for log in logs %}
<tr>
    <td>{{ log.type }}</td>
    <td>{% if log.description %}{{ log.description }}{% else %}بدون توضیحات{% endif %}</td>
    <td>{% if log.corrective_actions %}{{ log.corrective_actions }}{% else %}بدون توضیحات{% endif %}</td>
    <td>{% if log.prevention_actions %}{{ log.prevention_actions }}{% else %}بدون توضیحات{% endif %}</td>
    <td>{{ log.created|to_jalali:'%Y/%m/%d - %H:%M' }}</td>
    <td>{% if log.effective == False %}خیر{% else %}بله{% endif %}</td>
</tr>
{% empty %}
</table>
<span class="message">اطلاعاتی موجود نیست.</span>
{% endfor %}

organization/templates/ProblemLogsActions.html
{% extends "base.html" %}
{% load static %}
{% block include %}
<link href="{% static "css/logs.css" %}" rel="stylesheet">
<link href="{% static "css/forms.css" %}" rel="stylesheet">
{% endblock %}
{% block content %}
<div id="mainContent">
    <form action="/export-pdf/problem_reps" method="get">
        {{ search_form.as_p }}
        {% csrf_token %}
        <input id="apply" type="submit" value="دانلود PDF">
    </form>
    <table>
        <tr>
            <th>اعلام کننده</th>
            <th>نوع خطا</th>
            <th>اقدامات اصلاحی</th>
            <th>اقدامات پیشگیری</th>
            <th>توضیحات</th>
            <th>تاریخ</th>
            <th>موثر بوده/نبوده</th>
            <th>عملیات</th>
        </tr>
        {% include "ProblemLogsActionsAJAX.html" %}
    </table>

    <div class="popUpSection">
        <div class="popUp">
            <span class="popUpTitle">سرویس انتخابی با موفقیت از لیست انتظار حذف شد.</span>
            <a href="/waiting" id="closeBtn" class="submit">بروزرسانی لیست</a>
        </div>
    </div>
</div>
<span id="loading" class="custom-loader"></span>
{{ search_form.media }}
{% endblock %}

{% block domready %}
<script>
    let page = 1;
    let empty_page = false;
    let block_request = false;

    $(window).scroll(function() {
        var margin = $(document).height() - $(window).height() - 50;
        if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
            block_request = true;
            page += 1;
            $.get('?page=' + page, function(data) {
                if(data == '') {
                    empty_page = true;
                }
                else {
                    block_request = false;
                    $(" table ").append(data);
                }
            });
        }
    });
</script>
<script src="{% static "js/search-form.js" %}"></script>
{% endblock %}

organization/templates/ProblemLogsActionsAJAX.html
{% load to_jalali_datetime %}
{% for log in logs %}
<tr>
    <td>{{ log.user }}</td>
    <td>{{ log.type }}</td>
    <td>{% if log.description %}{{ log.description }}{% else %}بدون توضیحات{% endif %}</td>
    <td>{% if log.corrective_actions %}{{ log.corrective_actions }}{% else %}بدون توضیحات{% endif %}</td>
    <td>{% if log.prevention_actions %}{{ log.prevention_actions }}{% else %}بدون توضیحات{% endif %}</td>
    <td>{{ log.created|to_jalali:'%Y/%m/%d - %H:%M' }}</td>
    <td>{% if log.effective == False %}خیر{% else %}بله{% endif %}</td>
    <td><i class="order-completed fi fi-rr-assessment-alt"></i></td>
</tr>
{% empty %}
</table>
<span class="message">اطلاعاتی موجود نیست.</span>
{% endfor %}

organization/templates/ProblemReport.html
{% extends "base.html" %}
{% load static %}
{% block include %}
<link href="{% static "css/forms.css" %}" rel="stylesheet">
{% endblock %}
{% block content %}
<form class="formBox" method="post">
    {% if message %}
    <span class="message" style="color: {{ status }};">{{ message }}</span>
    {% endif %}
    {{ form.as_p }}
    {% csrf_token %}
    <input id="apply" type="submit" value="ثبت">
</form>
{% endblock %}

{% block domready %}
<script>

</script>
{% endblock %}

organization/templates/VacationDetail.html
{% extends "base.html" %}
{% load static %}
{% load to_jalali_datetime %}
{% block include %}
<link href="{% static "css/forms.css" %}" rel="stylesheet">
<link href="{% static "css/log-detail.css" %}" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="log-detail-box">
    <p><span class="log-label">نام متقاضی:</span><span class="log-text">{{ instance.user }}</span></p>
    <p><span class="log-label">نام جایگزین:</span><span class="log-text">{{ instance.alternative }}</span></p>
    <p><span class="log-label">تاریخ ثبت:</span><span class="log-text">{{ instance.created|to_jalali:'%Y/%m/%d - %H:%M' }}</span></p>
    <p><span class="log-label">تاریخ شروع:</span><span class="log-text">{{ instance.start_date|to_jalali:'%Y/%m/%d - %H:%M' }}</span></p>
    <p><span class="log-label">تاریخ پایان:</span><span class="log-text">{{ instance.end_date|to_jalali:'%Y/%m/%d - %H:%M' }}</span></p>
    <p><span class="log-label">نوع مرخصی:</span><span class="log-text">{{ instance.type }}</span></p>
    <p><span class="log-label">مدت:</span><span class="log-text">{{ instance.duration }}</span></p>
    <p><span class="log-label">توضیحات:</span><span class="log-text">{% if instance.description %}{{ instance.description }}{% else %}بدون توضیحات{% endif %}</span></p>
</div>
{% with permissions=request.user.get_all_permissions %}
{% if "organization.change_vacationrequest" in permissions or instance.alternative == request.user %}
<form class="formBox" method="post">
    {% if message %}
    <span class="message" style="color: {{ status }};">{{ message }}</span>
    {% endif %}
    {{ form.as_p }}
    {% csrf_token %}
    <input id="apply" type="submit" value="اعمال تغییرات">
</form>
{% endif %}
{% endwith %}
{% endblock %}

{% block domready %}
<script>

</script>
{% endblock %}

organization/templates/VacationLogs.html
{% extends "base.html" %}
{% load static %}
{% block include %}
<link href="{% static "css/logs.css" %}" rel="stylesheet">
{% endblock %}
{% block content %}
<div id="mainContent">
    <table>
        <tr>
            <th>جایگزین</th>
            <th>نوع</th>
            <th>شروع</th>
            <th>پایان</th>
            <th>مدت</th>
            <th>توضیحات</th>
            <th>ثبت</th>
            <th>وضعیت</th>
        </tr>
        {% include "VacationLogsAJAX.html" %}
    </table>

    <div class="popUpSection">
        <div class="popUp">
            <span class="popUpTitle">سرویس انتخابی با موفقیت از لیست انتظار حذف شد.</span>
            <a href="/waiting" id="closeBtn" class="submit">بروزرسانی لیست</a>
        </div>
    </div>
</div>
<span id="loading" class="custom-loader"></span>
{% endblock %}

{% block domready %}
<script>
    let page = 1;
    let empty_page = false;
    let block_request = false;

    $(window).scroll(function() {
        var margin = $(document).height() - $(window).height() - 50;
        if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
            block_request = true;
            page += 1;
            $.get('?page=' + page, function(data) {
                if(data == '') {
                    empty_page = true;
                }
                else {
                    block_request = false;
                    $(" table ").append(data);
                }
            });
        }
    });
</script>
{% endblock %}

organization/templates/VacationLogsAJAX.html
{% load to_jalali_datetime %}
{% for log in logs %}
<tr style="background-color: {% if log.status == 'رد شده' or log.status == 'رد جانشین' %}#ff000036{% elif log.status == 'موافقت شده' %}#32c91736{% else %}white{% endif %};">
    <td>{{ log.alternative }}</td>
    <td>{{ log.type }}</td>
    <td>{{ log.start_date|to_jalali:'%Y/%m/%d - %H:%M' }}</td>
    <td>{{ log.end_date|to_jalali:'%Y/%m/%d - %H:%M' }}</td>
    <td>{{ log.duration }}</td>
    <td>{% if log.description %}{{ log.description }}{% else %}بدون توضیحات{% endif %}</td>
    <td>{{ log.created|to_jalali:'%Y/%m/%d' }}</td>
    <td>{{ log.status }}</td>
</tr>
{% empty %}
</table>
<span class="message">اطلاعاتی موجود نیست.</span>
{% endfor %}

organization/templates/VacationLogsActions.html
{% extends "base.html" %}
{% load static %}
{% block include %}
<link href="{% static "css/logs.css" %}" rel="stylesheet">
<link href="{% static "css/forms.css" %}" rel="stylesheet">
{% endblock %}
{% block content %}
<div id="mainContent">
    {% if action_mode == 'boss' %}
    <form action="/export-pdf/vacation_reqs" method="get">
        {{ search_form.as_p }}
        {% csrf_token %}
        <input id="apply" type="submit" value="دانلود PDF">
    </form>
    {% endif %}
    <table>
        <tr>
            <th>متقاضی</th>
            <th>جایگزین</th>
            <th>نوع</th>
            <th>شروع</th>
            <th>پایان</th>
            <th>مدت</th>
            <th>توضیحات</th>
            <th>ثبت</th>
            <th>وضعیت</th>
            <th>عملیات</th>
        </tr>
        {% include "VacationLogsActionsAJAX.html" %}
    </table>

    <div class="popUpSection">
        <div class="popUp">
            <span class="popUpTitle">سرویس انتخابی با موفقیت از لیست انتظار حذف شد.</span>
            <a href="/waiting" id="closeBtn" class="submit">بروزرسانی لیست</a>
        </div>
    </div>
</div>
<span id="loading" class="custom-loader"></span>
{{ search_form.media }}
{% endblock %}

{% block domready %}
<script>
    let page = 1;
    let empty_page = false;
    let block_request = false;

    $(window).scroll(function() {
        var margin = $(document).height() - $(window).height() - 50;
        if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
            block_request = true;
            page += 1;
            $.get('?page=' + page, function(data) {
                if(data == '') {
                    empty_page = true;
                }
                else {
                    block_request = false;
                    $(" table ").append(data);
                }
            });
        }
    });

</script>
<script src="{% static "js/search-form.js" %}"></script>
{% endblock %}

organization/templates/VacationLogsActionsAJAX.html
{% load to_jalali_datetime %}
{% for log in logs %}
<tr style="background-color: {% if log.status == 'رد شده' or log.status == 'رد جانشین' %}#ff000036{% elif log.status == 'موافقت شده' %}#32c91736{% else %}white{% endif %};">
    <td>{{ log.user }}</td>
    <td>{{ log.alternative }}</td>
    <td>{{ log.type }}</td>
    <td>{{ log.start_date|to_jalali:'%Y/%m/%d - %H:%M' }}</td>
    <td>{{ log.end_date|to_jalali:'%Y/%m/%d - %H:%M' }}</td>
    <td>{{ log.duration }}</td>
    <td>{% if log.description %}{{ log.description }}{% else %}بدون توضیحات{% endif %}</td>
    <td>{{ log.created|to_jalali:'%Y/%m/%d - %H:%M' }}</td>
    <td>{{ log.status }}</td>
    <td>
        <a class="a-btn" href="{% if action_mode == 'boss' %}{% url 'organization:vacation_request_review' log.id %}{% else %}{% url 'organization:alternative_request_review' log.id %}{% endif %}">
            <i class="order-completed fi fi-rr-assessment-alt"></i>
        </a>
    </td>
</tr>
{% empty %}
</table>
<span class="message">اطلاعاتی موجود نیست.</span>
{% endfor %}

organization/templates/VacationRequest.html
{% extends "base.html" %}
{% load static %}
{% block include %}
<link href="{% static "css/forms.css" %}" rel="stylesheet">
{% endblock %}
{% block content %}
<form class="formBox" method="post">
    {% if message %}
    <span class="message" style="color: {{ status }};">{{ message }}</span>
    {% endif %}
    {{ form.as_p }}
    {% csrf_token %}
    <input id="apply" type="submit" value="ثبت">
</form>
{{ form.media }}
{% endblock %}

{% block domready %}
<script>
    jalaliDatepicker.updateOptions({"minDate": "today"});
    $(" #type ").change(function() {
        if( $(this).val() == "روزانه") {
            jalaliDatepicker.updateOptions({"time": false});
        } else {
            jalaliDatepicker.updateOptions({"time": true});
        }
    });
</script>
<script src="{% static "js/search-form.js" %}"></script>
{% endblock %}